export ZSH="/Users/wellis/.oh-my-zsh"

ZSH_THEME="tahnok4"

plugins=(zsh-syntax-highlighting virtualenv fzf)
source $ZSH/oh-my-zsh.sh

#pyenv 
#export PATH="/home/wellis/.pyenv/bin:$PATH"
PYENV_ROOT="$HOME/.pyenv"
PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init --no-rehash - zsh)"
eval "$(pyenv virtualenv-init -)"

alias g="git"
alias c="code ."
#alias first-push='git push -u origin $(git_current_branch)'
alias vim="nvim"

# make less exit if less than 1 page
export LESS="-FRSX"

# ripgrep / fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND="rg --files --hidden"

# nvm / node
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# gcloud
source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"
source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"

# psql via libpq
export PATH="/usr/local/opt/libpq/bin:$PATH"

# pipx binaries
export PATH="/Users/wellis/.local/bin:$PATH"

export EDITOR='nvim'
export VISUAL='nvim'

function noti() {
	TITLE="${2:=cli}"
	MSG="${1:=something done}"
	osascript -e "display notification \"${MSG}\" with title \"${TITLE}\""
}

alias mv="mv -iv"
alias cp="cp -iv"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
